import { MasteringPreset } from '../types';

export type PresetCategory = 'All' | 'Mastering' | 'Mixing' | 'Saturation';

export const PRESET_CATEGORIES: { id: PresetCategory; label: string; count?: number; description: string }[] = [
  { id: 'All', label: 'All Profiles', description: 'Complete library of calibrated DSP curves' },
  { id: 'Mastering', label: 'Mastering', description: 'Streaming targets, peak limiters, and competitive loudness' },
  { id: 'Mixing', label: 'Mixing', description: 'Bus glue, dynamic control, and instrument clarity' },
  { id: 'Saturation', label: 'Saturation', description: 'Analog console warmth, tape harmonic color, and tube drive' },
];

export const DEFAULT_PARAMS = {
  low: 0,
  mid: 0,
  high: 0,
  threshold: -24,
  ratio: 3,
  gain: 0,
};

export const MASTERING_PRESETS: MasteringPreset[] = [
  // ================= MASTERING CATEGORY =================
  {
    id: 'default',
    name: 'Neutral / Transparent',
    category: 'Mastering',
    description: 'Clean balanced starting point with zero coloration and mild transparent leveling.',
    targetLufs: -16.0,
    isPro: false,
    params: {
      low: 0,
      mid: 0,
      high: 0,
      threshold: -24,
      ratio: 2.5,
      gain: 2.0,
    },
  },
  {
    id: 'maximum-loudness',
    name: 'Streaming Maximizer (-14 LUFS)',
    category: 'Mastering',
    description: 'Calibrated to Spotify/Apple Music standards with transparent brickwall peak control.',
    targetLufs: -14.0,
    isPro: false,
    params: {
      low: 1.8,
      mid: -0.6,
      high: 2.2,
      threshold: -18,
      ratio: 3.5,
      gain: 5.2,
    },
  },
  {
    id: 'edm-punch',
    name: 'Club & EDM Punch (-9.5 LUFS)',
    category: 'Mastering',
    description: 'Tight sub-bass drive, crisp high air, and aggressive dynamic limiting for festival systems.',
    targetLufs: -9.5,
    isPro: true,
    params: {
      low: 3.5,
      mid: -2.0,
      high: 3.0,
      threshold: -20,
      ratio: 4.5,
      gain: 5.8,
    },
  },
  {
    id: 'trap-heavy-bass',
    name: 'Hip-Hop & Trap Sub-Drive',
    category: 'Mastering',
    description: 'Powerful 808 sub-shelf enhancement with vocal clarity contouring and firm peak control.',
    targetLufs: -10.5,
    isPro: true,
    params: {
      low: 4.2,
      mid: -1.8,
      high: 1.5,
      threshold: -18,
      ratio: 4.0,
      gain: 4.8,
    },
  },
  {
    id: 'broadcast-podcast',
    name: 'Broadcast & Speech (-16 LUFS)',
    category: 'Mastering',
    description: 'Speech intelligibility profile with high vocal ratio and strict compliance ceiling.',
    targetLufs: -16.0,
    isPro: false,
    params: {
      low: -1.5,
      mid: 1.8,
      high: 1.5,
      threshold: -30,
      ratio: 5.0,
      gain: 6.0,
    },
  },
  {
    id: 'acoustic-clarity',
    name: 'Acoustic & Classical Clarity',
    category: 'Mastering',
    description: 'Preserves delicate micro-dynamics with subtle high-shelf sparkle and gentle 1.8:1 leveling.',
    targetLufs: -16.5,
    isPro: false,
    params: {
      low: 0.8,
      mid: 0.5,
      high: 2.2,
      threshold: -28,
      ratio: 1.8,
      gain: 1.5,
    },
  },

  // ================= MIXING CATEGORY =================
  {
    id: 'vocal-presence',
    name: 'Vocal Bus Focus & Air',
    category: 'Mixing',
    description: 'Accentuates vocal presence at 1.2 kHz, scoops muddy low mids, and adds silk top air.',
    targetLufs: -14.5,
    isPro: false,
    params: {
      low: -1.0,
      mid: 2.8,
      high: 2.2,
      threshold: -24,
      ratio: 3.2,
      gain: 3.0,
    },
  },
  {
    id: 'drum-bus-glue',
    name: 'Drum Bus Glue & Snap',
    category: 'Mixing',
    description: 'Snappy transient punch with cohesive 4:1 compression to lock the kick and snare together.',
    targetLufs: -13.0,
    isPro: true,
    params: {
      low: 2.4,
      mid: -1.2,
      high: 1.6,
      threshold: -22,
      ratio: 4.0,
      gain: 3.6,
    },
  },
  {
    id: 'stereo-bus-tightener',
    name: 'Master Bus Mix Tightener',
    category: 'Mixing',
    description: 'Subtle 2:1 glue compression that locks elements together without crushing dynamics.',
    targetLufs: -15.0,
    isPro: false,
    params: {
      low: 1.2,
      mid: 0.2,
      high: 1.5,
      threshold: -26,
      ratio: 2.0,
      gain: 2.2,
    },
  },
  {
    id: 'bass-sub-control',
    name: 'Bass & Sub-Range Tightener',
    category: 'Mixing',
    description: 'Solidifies low frequencies with high ratio containment and clean low-mid attenuation.',
    targetLufs: -13.5,
    isPro: true,
    params: {
      low: 3.8,
      mid: -2.2,
      high: -0.5,
      threshold: -20,
      ratio: 4.8,
      gain: 3.2,
    },
  },
  {
    id: 'guitar-instrument-bus',
    name: 'Guitar & Synth Articulation',
    category: 'Mixing',
    description: 'Wide mid-range harmonic push and crisp transient definition for dense rhythm tracks.',
    targetLufs: -14.0,
    isPro: false,
    params: {
      low: -0.8,
      mid: 2.0,
      high: 2.4,
      threshold: -25,
      ratio: 2.8,
      gain: 2.5,
    },
  },

  // ================= SATURATION CATEGORY =================
  {
    id: 'warm-analog-tape',
    name: 'Warm Analog Tape Color',
    category: 'Saturation',
    description: 'Rich low-end tape bump, 2nd harmonic warmth, and smooth analog high frequency roll-off.',
    targetLufs: -13.8,
    isPro: true,
    params: {
      low: 3.2,
      mid: -1.0,
      high: 1.2,
      threshold: -21,
      ratio: 3.2,
      gain: 4.0,
    },
  },
  {
    id: 'tube-console-drive',
    name: 'Tube Console Harmonic Drive',
    category: 'Saturation',
    description: 'Even-order harmonic saturation with warm low-shelf richness and silky top-end sheen.',
    targetLufs: -13.0,
    isPro: true,
    params: {
      low: 2.8,
      mid: 1.2,
      high: 2.0,
      threshold: -19,
      ratio: 3.8,
      gain: 4.5,
    },
  },
  {
    id: 'vintage-70s-transformer',
    name: '70s Vintage Transformer',
    category: 'Saturation',
    description: 'Classic British console iron transformer color with focused mid punch and analog grit.',
    targetLufs: -12.5,
    isPro: true,
    params: {
      low: 2.2,
      mid: 2.2,
      high: 0.8,
      threshold: -20,
      ratio: 4.2,
      gain: 4.2,
    },
  },
  {
    id: 'modern-harmonic-excite',
    name: 'Modern Harmonic Exciter',
    category: 'Saturation',
    description: 'Excites upper octave harmonics for crystalline clarity without harshness or sibilance.',
    targetLufs: -14.0,
    isPro: false,
    params: {
      low: 0.5,
      mid: 0.8,
      high: 3.5,
      threshold: -24,
      ratio: 2.2,
      gain: 2.8,
    },
  },
];
