import { MasteringPreset } from '../types';

export type PresetCategory = 'All' | 'Mastering' | 'Mixing' | 'Saturation';

export const PRESET_CATEGORIES: { id: PresetCategory; label: string; count?: number; description: string }[] = [
  { id: 'All', label: 'All Profiles', description: 'Complete library of calibrated DSP curves' },
  { id: 'Mastering', label: 'Mastering', description: 'Streaming targets, peak limiters, and competitive loudness' },
  { id: 'Mixing', label: 'Mixing', description: 'Bus glue, dynamic control, and instrument clarity' },
  { id: 'Saturation', label: 'Saturation', description: 'Analog console warmth, tape harmonic color, and tube drive' },
];

export const DEFAULT_PARAMS = {
  low: 0,
  mid: 0,
  high: 0,
  threshold: -24,
  ratio: 3,
  gain: 0,
};

export const MASTERING_PRESETS: MasteringPreset[] = [
  {
    id: 'default',
    name: 'Neutral / Transparent',
    category: 'Mastering',
    description: 'Clean balanced starting point with zero coloration and mild transparent leveling.',
    targetLufs: -16.0,
    isPro: false,
    params: { low: 0, mid: 0, high: 0, threshold: -24, ratio: 2.5, gain: 2.0 },
  },
  {
    id: 'maximum-loudness',
    name: 'Streaming Maximizer',
    category: 'Mastering',
    description: 'Controlled loudness lift with a balanced top end and conservative peak management.',
    targetLufs: -14.0,
    isPro: false,
    params: { low: 1.8, mid: -0.6, high: 2.2, threshold: -18, ratio: 3.5, gain: 5.2 },
  },
  {
    id: 'edm-punch',
    name: 'Club & EDM Punch',
    category: 'Mastering',
    description: 'Tight sub-bass drive, crisp high air, and assertive dynamic control for energetic material.',
    targetLufs: -9.5,
    isPro: false,
    params: { low: 3.5, mid: -2.0, high: 3.0, threshold: -20, ratio: 4.5, gain: 5.8 },
  },
  {
    id: 'trap-heavy-bass',
    name: 'Hip-Hop & Trap Sub-Drive',
    category: 'Mastering',
    description: 'Powerful 808-oriented low-end contour with vocal clarity and firm dynamic control.',
    targetLufs: -10.5,
    isPro: false,
    params: { low: 4.2, mid: -1.8, high: 1.5, threshold: -18, ratio: 4.0, gain: 4.8 },
  },
  {
    id: 'broadcast-podcast',
    name: 'Broadcast & Speech',
    category: 'Mastering',
    description: 'Voice-forward contour with firm leveling and controlled low-end buildup.',
    targetLufs: -16.0,
    isPro: false,
    params: { low: -1.5, mid: 1.8, high: 1.5, threshold: -30, ratio: 5.0, gain: 6.0 },
  },
  {
    id: 'acoustic-clarity',
    name: 'Acoustic & Classical Clarity',
    category: 'Mastering',
    description: 'Preserves delicate micro-dynamics with subtle high-shelf sparkle and gentle leveling.',
    targetLufs: -16.5,
    isPro: false,
    params: { low: 0.8, mid: 0.5, high: 2.2, threshold: -28, ratio: 1.8, gain: 1.5 },
  },
  {
    id: 'pop-vocal-air',
    name: 'Modern Pop Vocal Air',
    category: 'Mastering',
    description: 'Open upper range and focused vocal mids with polished, controlled dynamics.',
    targetLufs: -14.0,
    isPro: false,
    params: { low: 0.4, mid: 1.7, high: 2.8, threshold: -20, ratio: 2.8, gain: 3.6 },
  },
  {
    id: 'indie-rock-open',
    name: 'Indie Rock Open Master',
    category: 'Mastering',
    description: 'Keeps transient character intact while adding a little weight and edge for dense guitars.',
    targetLufs: -12.5,
    isPro: false,
    params: { low: 1.7, mid: 0.9, high: 1.8, threshold: -22, ratio: 2.4, gain: 3.2 },
  },
  {
    id: 'rnb-smooth',
    name: 'R&B Smooth Depth',
    category: 'Mastering',
    description: 'Silky top end, centered vocals, and soft low-frequency density for modern R&B.',
    targetLufs: -13.5,
    isPro: false,
    params: { low: 2.4, mid: 0.6, high: 1.1, threshold: -21, ratio: 2.7, gain: 3.4 },
  },
  {
    id: 'cinematic-wide',
    name: 'Cinematic Wide & Natural',
    category: 'Mastering',
    description: 'Gentle bus control designed to preserve depth, ambience, and large transient movement.',
    targetLufs: -18.0,
    isPro: false,
    params: { low: 0.7, mid: -0.2, high: 1.0, threshold: -30, ratio: 1.6, gain: 0.8 },
  },
  {
    id: 'vocal-presence',
    name: 'Vocal Bus Focus & Air',
    category: 'Mixing',
    description: 'Accentuates vocal presence, reduces muddy low mids, and adds controlled top air.',
    targetLufs: -14.5,
    isPro: false,
    params: { low: -1.0, mid: 2.8, high: 2.2, threshold: -24, ratio: 3.2, gain: 3.0 },
  },
  {
    id: 'drum-bus-glue',
    name: 'Drum Bus Glue & Snap',
    category: 'Mixing',
    description: 'Snappy transient punch with cohesive compression to lock kick and snare together.',
    targetLufs: -13.0,
    isPro: false,
    params: { low: 2.4, mid: -1.2, high: 1.6, threshold: -22, ratio: 4.0, gain: 3.6 },
  },
  {
    id: 'stereo-bus-tightener',
    name: 'Master Bus Mix Tightener',
    category: 'Mixing',
    description: 'Subtle glue compression that locks elements together without crushing dynamics.',
    targetLufs: -15.0,
    isPro: false,
    params: { low: 1.2, mid: 0.2, high: 1.5, threshold: -26, ratio: 2.0, gain: 2.2 },
  },
  {
    id: 'bass-sub-control',
    name: 'Bass & Sub-Range Tightener',
    category: 'Mixing',
    description: 'Solidifies low frequencies with high-ratio containment and clean low-mid attenuation.',
    targetLufs: -13.5,
    isPro: false,
    params: { low: 3.8, mid: -2.2, high: -0.5, threshold: -20, ratio: 4.8, gain: 3.2 },
  },
  {
    id: 'guitar-instrument-bus',
    name: 'Guitar & Synth Articulation',
    category: 'Mixing',
    description: 'Wide mid-range harmonic push and crisp transient definition for dense rhythm tracks.',
    targetLufs: -14.0,
    isPro: false,
    params: { low: -0.8, mid: 2.0, high: 2.4, threshold: -25, ratio: 2.8, gain: 2.5 },
  },
  {
    id: 'mix-clarity-glue',
    name: 'Mix Clarity Glue',
    category: 'Mixing',
    description: 'Light broadband glue with a small presence lift for a finished two-bus feel.',
    targetLufs: -14.0,
    isPro: false,
    params: { low: 0.6, mid: 1.0, high: 1.4, threshold: -25, ratio: 2.2, gain: 2.0 },
  },
  {
    id: 'lofi-bus-color',
    name: 'Lo-Fi Bus Color',
    category: 'Mixing',
    description: 'Soft low-mid density and rolled top-end contour for intentionally textured arrangements.',
    targetLufs: -15.0,
    isPro: false,
    params: { low: 2.0, mid: 1.3, high: -1.8, threshold: -23, ratio: 2.6, gain: 2.8 },
  },
  {
    id: 'warm-analog-tape',
    name: 'Warm Analog Tape Color',
    category: 'Saturation',
    description: 'Rich low-end density, second-harmonic warmth, and a smoother upper range.',
    targetLufs: -13.8,
    isPro: false,
    params: { low: 3.2, mid: -1.0, high: 1.2, threshold: -21, ratio: 3.2, gain: 4.0 },
  },
  {
    id: 'tube-console-drive',
    name: 'Tube Console Harmonic Drive',
    category: 'Saturation',
    description: 'Even-order harmonic emphasis with warm low-shelf richness and silky top-end sheen.',
    targetLufs: -13.0,
    isPro: false,
    params: { low: 2.8, mid: 1.2, high: 2.0, threshold: -19, ratio: 3.8, gain: 4.5 },
  },
  {
    id: 'vintage-70s-transformer',
    name: '70s Vintage Transformer',
    category: 'Saturation',
    description: 'Focused mid punch and controlled grit inspired by classic transformer coloration.',
    targetLufs: -12.5,
    isPro: false,
    params: { low: 2.2, mid: 2.2, high: 0.8, threshold: -20, ratio: 4.2, gain: 4.2 },
  },
  {
    id: 'modern-harmonic-excite',
    name: 'Modern Harmonic Exciter',
    category: 'Saturation',
    description: 'Upper-octave excitement for crystalline detail without pushing harshness too far.',
    targetLufs: -14.0,
    isPro: false,
    params: { low: 0.5, mid: 0.8, high: 3.5, threshold: -24, ratio: 2.2, gain: 2.8 },
  },
  {
    id: 'console-thickness',
    name: 'Console Thickness',
    category: 'Saturation',
    description: 'Gentle low-mid weight and soft compression for a dense, forward console-style finish.',
    targetLufs: -13.0,
    isPro: false,
    params: { low: 2.0, mid: 1.8, high: 0.4, threshold: -22, ratio: 3.1, gain: 3.2 },
  },
  {
    id: 'bright-tape-finish',
    name: 'Bright Tape Finish',
    category: 'Saturation',
    description: 'Tape-style body with a little extra air for polished modern arrangements.',
    targetLufs: -13.5,
    isPro: false,
    params: { low: 2.6, mid: -0.4, high: 2.4, threshold: -22, ratio: 3.0, gain: 3.6 },
  },
];
