import { MasteringPreset } from '../types';

export const DEFAULT_PARAMS = {
  low: 0,
  mid: 0,
  high: 0,
  threshold: -24,
  ratio: 3,
  gain: 0,
};

export const MASTERING_PRESETS: MasteringPreset[] = [
  {
    id: 'default',
    name: 'Neutral / Transparent',
    category: 'General',
    description: 'Clean balanced starting point with minimal coloration and mild compression.',
    targetLufs: -16.0,
    isPro: false,
    params: {
      low: 0,
      mid: 0,
      high: 0,
      threshold: -24,
      ratio: 2.5,
      gain: 2.0,
    },
  },
  {
    id: 'warm-analog',
    name: 'Warm Analog Console',
    category: 'Character',
    description: 'Rich low-end shelf warmth, gentle mid scoop, and smooth studio air frequencies.',
    targetLufs: -14.0,
    isPro: true,
    params: {
      low: 2.8,
      mid: -1.5,
      high: 1.8,
      threshold: -22,
      ratio: 3.2,
      gain: 3.5,
    },
  },
  {
    id: 'edm-punch',
    name: 'EDM / Club Punch & Air',
    category: 'Electronic',
    description: 'Tight sub-bass boost, crisp highs, and aggressive dynamic compression for maximum energy.',
    targetLufs: -9.5,
    isPro: true,
    params: {
      low: 3.5,
      mid: -2.0,
      high: 3.0,
      threshold: -20,
      ratio: 4.5,
      gain: 5.0,
    },
  },
  {
    id: 'acoustic-clarity',
    name: 'Acoustic & Folk Clarity',
    category: 'Organic',
    description: 'Transparent high shelf sparkle, neutral mids, and gentle ratio to preserve natural dynamics.',
    targetLufs: -16.5,
    isPro: false,
    params: {
      low: 0.8,
      mid: 0.5,
      high: 2.2,
      threshold: -28,
      ratio: 1.8,
      gain: 1.5,
    },
  },
  {
    id: 'vocal-presence',
    name: 'Vocal Forward Master',
    category: 'Vocal',
    description: 'Accentuates vocal clarity at 1.2 kHz with controlled low end and bright presence.',
    targetLufs: -14.5,
    isPro: false,
    params: {
      low: -0.5,
      mid: 2.5,
      high: 2.0,
      threshold: -25,
      ratio: 3.0,
      gain: 3.0,
    },
  },
  {
    id: 'trap-heavy-bass',
    name: 'Hip-Hop & Trap Heavy',
    category: 'Urban',
    description: 'Powerful 120Hz sub-shelf drive, slightly scooped vocal air, and firm peak limiting.',
    targetLufs: -10.0,
    isPro: true,
    params: {
      low: 4.2,
      mid: -1.8,
      high: 1.2,
      threshold: -18,
      ratio: 4.0,
      gain: 4.5,
    },
  },
  {
    id: 'broadcast-podcast',
    name: 'Broadcast & Podcast Voice',
    category: 'Speech',
    description: 'Optimized voice intelligibility with high speech ratio and controlled dynamic range.',
    targetLufs: -16.0,
    isPro: false,
    params: {
      low: -1.5,
      mid: 1.8,
      high: 1.5,
      threshold: -30,
      ratio: 5.0,
      gain: 6.0,
    },
  },
  {
    id: 'maximum-loudness',
    name: 'Streaming Maximizer (-14 LUFS)',
    category: 'Loudness',
    description: 'Optimized high gain makeup calibrated to standard streaming platforms with brickwall ceiling.',
    targetLufs: -14.0,
    isPro: true,
    params: {
      low: 2.0,
      mid: -0.8,
      high: 2.5,
      threshold: -16,
      ratio: 6.0,
      gain: 7.5,
    },
  },
];
